Stratax: stratax::ops::detail Namespace Reference
stratax::ops::detail Namespace Reference
Functions
template<std::size_t N, std::size_t... Is>
stratax::core::Shape shape_from_slices_impl (const std::array< stratax::core::Slice, N > &ranges, std::index_sequence< Is... >)
Builds a shape from a compile-time slice array.
template<std::size_t N>
stratax::core::Shape shape_from_slices (const std::array< stratax::core::Slice, N > &ranges)
Builds a shape from a slice array.
Function Documentation
shape_from_slices()
template<std::size_t N> stratax::core::Shape stratax::ops::detail::shape_from_slices (const std::array< stratax::core::Slice, N > & ranges)
Builds a shape from a slice array.
Template Parameters
N Number of dimensions.
Parameters
ranges Slice ranges.
Returns
Shape whose dimensions match the slice extents.
Definition at line 45 of file Slice.hpp.
References shape_from_slices_impl().
Referenced by slice().
shape_from_slices_impl()
template<std::size_t N, std::size_t... Is> stratax::core::Shape stratax::ops::detail::shape_from_slices_impl (const std::array< stratax::core::Slice, N > & ranges, std::index_sequence< Is... >)
Builds a shape from a compile-time slice array.
Template Parameters
N Number of dimensions.
Is Index sequence used to expand the slice array.
Parameters
ranges Slice ranges.
Returns
Shape whose dimensions match the slice extents.
Definition at line 29 of file Slice.hpp.
Referenced by shape_from_slices().