from .matrix import Matrix
from .tensor import Tensor
from .vector import Vector


def to_vector(arr: Vector | Matrix | Tensor) -> Vector: ...
def to_matrix(arr: Vector | Matrix | Tensor) -> Matrix: ...
def to_tensor(arr: Vector | Matrix | Tensor) -> Tensor: ...
