from collections.abc import Iterable, Iterator
from typing import overload

from .shape import Shape
from .tensor import Tensor
from .vector import Vector


class Matrix:
    """Rank-2 row-major floating-point array with non-negative dimensions."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: "Matrix") -> None: ...
    @overload
    def __init__(self, shape: Shape) -> None: ...
    @overload
    def __init__(self, rows: int, cols: int) -> None: ...
    @overload
    def __init__(self, rows: int, cols: int, value: float) -> None: ...
    @overload
    def __init__(self, values: Iterable[Iterable[float]]) -> None: ...

    @property
    def size(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def empty(self) -> bool: ...
    @property
    def rows(self) -> int: ...
    @property
    def cols(self) -> int: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def strides(self) -> list[int]: ...

    def fill(self, value: float) -> None: ...
    def tolist(self) -> list[list[float]]: ...
    def reshape(self, shape: Shape | Iterable[int]) -> Tensor: ...
    def flatten(self) -> Vector: ...
    def __len__(self) -> int: ...

    @overload
    def __getitem__(self, index: tuple[int, int]) -> float: ...
    @overload
    def __getitem__(self, index: slice | tuple[int | slice, int | slice]) -> "Matrix": ...

    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: "Matrix | float") -> "Matrix": ...
    def __radd__(self, other: float) -> "Matrix": ...
    def __sub__(self, other: "Matrix | float") -> "Matrix": ...
    def __rsub__(self, other: float) -> "Matrix": ...
    def __mul__(self, other: "Matrix | float") -> "Matrix": ...
    def __rmul__(self, other: float) -> "Matrix": ...
    def __truediv__(self, other: "Matrix | float") -> "Matrix": ...
    def __rtruediv__(self, other: float) -> "Matrix": ...
    def __iadd__(self, other: "Matrix | float") -> "Matrix": ...
    def __isub__(self, other: "Matrix | float") -> "Matrix": ...
    def __imul__(self, other: "Matrix | float") -> "Matrix": ...
    def __itruediv__(self, other: "Matrix | float") -> "Matrix": ...
    def __pos__(self) -> "Matrix": ...
    def __neg__(self) -> "Matrix": ...
    def __repr__(self) -> str: ...
