"""Reduction helpers.

This module exposes Python-facing reduction helpers that operate on Stratax
wrapper containers and return either Python scalars or wrapped Stratax tensors.
"""

from .matrix import Matrix
from .tensor import Tensor
from .vector import Vector


def sum(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...
def prod(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...
def max(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...
def min(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...
def argmax(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> int | Tensor: ...
def argmin(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> int | Tensor: ...
def mean(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...
def var(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...
def std(arr: Vector | Matrix | Tensor, axis: int | None = None, keepdims: bool = False) -> float | Tensor: ...


__all__ = ["sum", "prod", "max", "min", "argmax", "argmin", "mean", "var", "std"]
