from collections.abc import Iterable, Iterator
from typing import overload


class Shape:
    """Stores non-negative dimensions for a Stratax array."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: "Shape") -> None: ...
    @overload
    def __init__(self, dims: Iterable[int]) -> None: ...
    @overload
    def __init__(self, first: int, second: int, /, *rest: int) -> None: ...

    @property
    def rank(self) -> int: ...
    @property
    def elements(self) -> int: ...
    @property
    def empty(self) -> bool: ...

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
