from collections.abc import Iterable, Iterator
from typing import overload

from .shape import Shape
from .tensor import Tensor


class Vector:
    """Rank-1 floating-point array with non-negative sizes."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: "Vector") -> None: ...
    @overload
    def __init__(self, shape: Shape) -> None: ...
    @overload
    def __init__(self, size: int) -> None: ...
    @overload
    def __init__(self, size: int, value: float) -> None: ...
    @overload
    def __init__(self, values: Iterable[float]) -> None: ...

    @property
    def size(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def empty(self) -> bool: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def strides(self) -> list[int]: ...

    def fill(self, value: float) -> None: ...
    def tolist(self) -> list[float]: ...
    def reshape(self, shape: Shape | Iterable[int]) -> Tensor: ...
    def flatten(self) -> "Vector": ...
    def __len__(self) -> int: ...

    @overload
    def __getitem__(self, index: int) -> float: ...
    @overload
    def __getitem__(self, index: slice) -> "Vector": ...

    def __setitem__(self, index: int, value: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: "Vector | float") -> "Vector": ...
    def __radd__(self, other: float) -> "Vector": ...
    def __sub__(self, other: "Vector | float") -> "Vector": ...
    def __rsub__(self, other: float) -> "Vector": ...
    def __mul__(self, other: "Vector | float") -> "Vector": ...
    def __rmul__(self, other: float) -> "Vector": ...
    def __truediv__(self, other: "Vector | float") -> "Vector": ...
    def __rtruediv__(self, other: float) -> "Vector": ...
    def __iadd__(self, other: "Vector | float") -> "Vector": ...
    def __isub__(self, other: "Vector | float") -> "Vector": ...
    def __imul__(self, other: "Vector | float") -> "Vector": ...
    def __itruediv__(self, other: "Vector | float") -> "Vector": ...
    def __pos__(self) -> "Vector": ...
    def __neg__(self) -> "Vector": ...
    def __repr__(self) -> str: ...
