from collections.abc import Iterable, Iterator
from typing import overload

from ...core.Shape import Shape
from ...core.Vector import Vector


class Tensor:
    """N-dimensional row-major floating-point array with non-negative dimensions."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: "Tensor") -> None: ...
    @overload
    def __init__(self, shape: Shape) -> None: ...
    @overload
    def __init__(self, shape: Shape, value: float) -> None: ...
    @overload
    def __init__(self, shape: Iterable[int]) -> None: ...
    @overload
    def __init__(self, shape: Iterable[int], value: float) -> None: ...

    @property
    def size(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def empty(self) -> bool: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def strides(self) -> list[int]: ...

    def fill(self, value: float) -> None: ...
    def tolist(self) -> list[float]: ...
    def reshape(self, shape: Shape | Iterable[int]) -> "Tensor": ...
    def flatten(self) -> Vector: ...
    def __len__(self) -> int: ...

    @overload
    def __getitem__(self, index: int | tuple[int, ...]) -> float: ...
    @overload
    def __getitem__(self, index: slice | tuple[int | slice, ...]) -> "Tensor": ...

    def __setitem__(self, index: int | tuple[int, ...], value: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: "Tensor | float") -> "Tensor": ...
    def __radd__(self, other: float) -> "Tensor": ...
    def __sub__(self, other: "Tensor | float") -> "Tensor": ...
    def __rsub__(self, other: float) -> "Tensor": ...
    def __mul__(self, other: "Tensor | float") -> "Tensor": ...
    def __rmul__(self, other: float) -> "Tensor": ...
    def __truediv__(self, other: "Tensor | float") -> "Tensor": ...
    def __rtruediv__(self, other: float) -> "Tensor": ...
    def __iadd__(self, other: "Tensor | float") -> "Tensor": ...
    def __isub__(self, other: "Tensor | float") -> "Tensor": ...
    def __imul__(self, other: "Tensor | float") -> "Tensor": ...
    def __itruediv__(self, other: "Tensor | float") -> "Tensor": ...
    def __pos__(self) -> "Tensor": ...
    def __neg__(self) -> "Tensor": ...
    def __repr__(self) -> str: ...